#!/bin/bash

# Run video-transcriber from Source on macOS
# Auto-generated by universal build system

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() {
    echo -e "${BLUE}[$(date +'%H:%M:%S')]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[$(date +'%H:%M:%S')] ✔${NC} $1"
}

print_error() {
    echo -e "${RED}[$(date +'%H:%M:%S')] ✗${NC} $1"
}

# Check if we're on macOS
if [ "$(uname)" != "Darwin" ]; then
    print_error "This script is for macOS only"
    exit 1
fi

print_status "🚀 Starting video-transcriber from source (macOS)..."

# Check dependencies
if ! command -v npm &> /dev/null; then
    print_error "npm is not installed. Install via Homebrew: brew install node"
    exit 1
fi

# Navigate to script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
    print_status "Installing dependencies..."
    npm install
fi

# Use all CPU cores
export UV_THREADPOOL_SIZE=$(sysctl -n hw.logicalcpu 2>/dev/null || echo 4)

# Run the app
if [ -f "package.json" ] && grep -q "\"dev\"" package.json; then
    npm run dev
elif [ -f "package.json" ] && grep -q "\"start\"" package.json; then
    npm start
else
    npx electron . --no-sandbox
fi

print_success "Application session ended"
