#!/bin/bash
set -euo pipefail

# Run video-transcriber from Source on Linux
# Auto-generated by universal build system

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() {
    echo -e "${BLUE}[$(date +'%H:%M:%S')]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[$(date +'%H:%M:%S')] ✔${NC} $1"
}

print_error() {
    echo -e "${RED}[$(date +'%H:%M:%S')] ✗${NC} $1"
}

# Check if we're on Linux
if [ "$(uname)" != "Linux" ]; then
    print_error "This script is for Linux only"
    exit 1
fi

print_status "🚀 Starting video-transcriber from source (Linux)..."

# Navigate to script directory first so all subsequent paths are correct
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Check dependencies
if ! command -v npm &> /dev/null; then
    print_error "npm is not installed. Install with: sudo apt install npm"
    exit 1
fi

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
    print_status "Installing dependencies..."
    npm install
fi

# Set Electron flags for Linux
export ELECTRON_FORCE_WINDOW_MENU_BAR=1
export ELECTRON_TRASH=gio

# Fix Electron sandbox permission issue on Linux
sudo sysctl -w kernel.unprivileged_userns_clone=1 2>/dev/null || true

# Use all CPU cores for builds
export UV_THREADPOOL_SIZE=$(nproc)

# Run the app from source (dev mode - unpackaged)
if [ -f "package.json" ] && grep -q "\"dev\"" package.json; then
    npm run dev
elif [ -f "package.json" ] && grep -q "\"start\"" package.json; then
    npm start
else
    npx electron . --no-sandbox
fi

print_success "Application session ended"
