// Universal API Provider Stack — LITE v2.0.0
// 17-provider registry. Alphabetical by displayName. Z.ai is the default provider.
// End-users configure keys via AI Modal settings; env vars auto-populate when available.

const PROVIDERS = [
  {
    id: 'anthropic-api',
    displayName: 'Anthropic (API)',
    type: 'api-key',
    envVarName: 'ANTHROPIC_API_KEY',
    baseUrl: 'https://api.anthropic.com',
    modelsPath: '/v1/models',
    chatPath: '/v1/messages',
    streamFormat: 'anthropic',
    authHeader: 'x-api-key',
    extraHeaders: { 'anthropic-version': '2023-06-01' },
    tokenField: 'max_tokens',
    stopField: 'stop_sequences',
    openaiCompat: false,
  },
  {
    id: 'anthropic-auth',
    displayName: 'Anthropic (Auth)',
    type: 'subscription',
    envVarName: 'CLAUDE_CODE_OAUTH_TOKEN',
    baseUrl: 'https://api.anthropic.com',
    modelsPath: '/v1/models?beta=true',
    chatPath: '/v1/messages?beta=true',
    streamFormat: 'anthropic',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    extraHeaders: {
      'anthropic-version': '2023-06-01',
      'anthropic-beta': 'oauth-2025-04-20',
    },
    tokenField: 'max_tokens',
    stopField: 'stop_sequences',
    openaiCompat: false,
  },
  {
    id: 'deepseek',
    displayName: 'DeepSeek',
    type: 'api-key',
    envVarName: 'DEEPSEEK_API_KEY',
    baseUrl: 'https://api.deepseek.com',
    modelsPath: '/v1/models',
    chatPath: '/v1/chat/completions',
    streamFormat: 'sse',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    tokenField: 'max_tokens',
    stopField: 'stop',
    openaiCompat: true,
  },
  {
    id: 'groq',
    displayName: 'Groq',
    type: 'api-key',
    envVarName: 'GROQ_API_KEY',
    baseUrl: 'https://api.groq.com/openai',
    modelsPath: '/v1/models',
    chatPath: '/v1/chat/completions',
    streamFormat: 'sse',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    tokenField: 'max_tokens',
    stopField: 'stop',
    openaiCompat: true,
  },
  {
    id: 'huggingface',
    displayName: 'HuggingFace',
    type: 'api-key',
    envVarName: 'HF_API_KEY',
    baseUrl: 'https://api-inference.huggingface.co',
    modelsPath: '/v1/models',
    chatPath: '/v1/chat/completions',
    streamFormat: 'sse',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    tokenField: 'max_new_tokens',
    stopField: 'stop',
    openaiCompat: true,
  },
  {
    id: 'meta',
    displayName: 'META',
    type: 'api-key',
    envVarName: 'LLAMA_API_KEY',
    baseUrl: 'https://api.llama.com',
    modelsPath: '/v1/models',
    chatPath: '/v1/chat/completions',
    streamFormat: 'sse',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    tokenField: 'max_tokens',
    stopField: 'stop',
    openaiCompat: true,
  },
  {
    id: 'mistral',
    displayName: 'Mistral',
    type: 'api-key',
    envVarName: 'MISTRAL_API_KEY',
    baseUrl: 'https://api.mistral.ai',
    modelsPath: '/v1/models',
    chatPath: '/v1/chat/completions',
    streamFormat: 'sse',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    tokenField: 'max_tokens',
    stopField: 'stop',
    openaiCompat: true,
  },
  {
    id: 'moonshot',
    displayName: 'Moonshot',
    type: 'api-key',
    envVarName: 'MOONSHOT_API_KEY',
    baseUrl: 'https://api.moonshot.ai',
    modelsPath: '/v1/models',
    chatPath: '/v1/chat/completions',
    streamFormat: 'sse',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    tokenField: 'max_tokens',
    stopField: 'stop',
    openaiCompat: true,
  },
  {
    id: 'nvidia',
    displayName: 'nVidia',
    type: 'api-key',
    envVarName: 'NVIDIA_API_KEY',
    baseUrl: 'https://integrate.api.nvidia.com',
    modelsPath: '/v1/models',
    chatPath: '/v1/chat/completions',
    streamFormat: 'sse',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    tokenField: 'max_tokens',
    stopField: 'stop',
    openaiCompat: true,
  },
  {
    id: 'ollama',
    displayName: 'Ollama (Local)',
    type: 'local',
    envVarName: 'OLLAMA_BASE_URL',
    baseUrl: 'http://localhost:11434',
    modelsPath: '/api/tags',
    chatPath: '/api/chat',
    streamFormat: 'ndjson',
    authHeader: null,
    tokenField: 'num_predict',
    stopField: 'stop',
    openaiCompat: false,
    nestParamsIn: 'options',
  },
  {
    id: 'openai',
    displayName: 'OpenAI',
    type: 'api-key',
    envVarName: 'OPENAI_API_KEY',
    baseUrl: 'https://api.openai.com',
    modelsPath: '/v1/models',
    chatPath: '/v1/chat/completions',
    streamFormat: 'sse',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    tokenField: 'max_tokens',
    stopField: 'stop',
    openaiCompat: true,
  },
  {
    id: 'openrouter',
    displayName: 'OpenRouter',
    type: 'api-key',
    envVarName: 'OPENROUTER_API_KEY',
    baseUrl: 'https://openrouter.ai/api',
    modelsPath: '/v1/models',
    chatPath: '/v1/chat/completions',
    streamFormat: 'sse',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    tokenField: 'max_tokens',
    stopField: 'stop',
    openaiCompat: true,
  },
  {
    id: 'perplexity',
    displayName: 'Perplexity',
    type: 'api-key',
    envVarName: 'PPLX_API_KEY',
    baseUrl: 'https://api.perplexity.ai',
    modelsPath: '/models',
    chatPath: '/chat/completions',
    streamFormat: 'sse',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    tokenField: 'max_tokens',
    stopField: 'stop',
    openaiCompat: true,
  },
  {
    id: 'pi',
    displayName: 'Pi.ai',
    type: 'api-key',
    envVarName: 'PI_API_KEY',
    baseUrl: 'https://api.inflection.ai',
    modelsPath: '/external/api/inference/models',
    chatPath: '/external/api/inference/openai/chat/completions',
    streamFormat: 'sse',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    tokenField: 'max_tokens',
    stopField: 'stop',
    openaiCompat: true,
  },
  {
    id: 'together',
    displayName: 'Together.AI',
    type: 'api-key',
    envVarName: 'TOGETHER_API_KEY',
    baseUrl: 'https://api.together.xyz',
    modelsPath: '/v1/models',
    chatPath: '/v1/chat/completions',
    streamFormat: 'sse',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    tokenField: 'max_tokens',
    stopField: 'stop',
    openaiCompat: true,
  },
  {
    id: 'xai',
    displayName: 'xAI',
    type: 'api-key',
    envVarName: 'XAI_API_KEY',
    baseUrl: 'https://api.x.ai',
    modelsPath: '/v1/models',
    chatPath: '/v1/chat/completions',
    streamFormat: 'sse',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    tokenField: 'max_tokens',
    stopField: 'stop',
    openaiCompat: true,
  },
  {
    id: 'zai',
    displayName: 'Z.ai',
    type: 'api-key',
    envVarName: 'ZAI_API_KEY',
    baseUrl: 'https://api.z.ai/api/coding/paas',
    modelsPath: '/v4/models',
    chatPath: '/v4/chat/completions',
    streamFormat: 'sse',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    tokenField: 'max_tokens',
    stopField: 'stop',
    openaiCompat: true,
  },
];

const DEFAULT_PROVIDER_ID = 'zai';

function getProviderById(id) {
  return PROVIDERS.find((p) => p.id === id) || null;
}

function listProviders() {
  return PROVIDERS.map((p) => ({ ...p, envPresent: !!process.env[p.envVarName] }));
}

module.exports = {
  PROVIDERS,
  DEFAULT_PROVIDER_ID,
  getProviderById,
  listProviders,
};
